### ISSUE TITLE
Localization not working even change system's language (iOS)

### ISSUE THREAD

**Issue by meunicorn** [freshworks/freshchat-flutter-sdk#10]
## Describe the bug
Localization not working even change system's language (iOS) , here's my code below :

```
Freshchat.init(
      FRESH_CHAT_APP_ID,
      FRESH_CHAT_APP_KEY,
      FRESH_CHAT_DOMAIN,
      stringsBundle: 'FreshchatI10n'
    );
```

## Steps to reproduce
```    
* Step 1 - change system language to japanese
* Step 2 - open app's freshchat , it shows in english.
```

## Expected behavior
shows in japanese

## Platform
- iOS

## Freshchat SDK version
- SDK version : 0.5.0
- Flutter version (if applicable) : 2.0.5

## Device information
- [Y] is reproducible on all devices? 

```
Provide device details here like
 * Device name iPhone
 * OS version iOS 14.4.2

```

**Comment by MuthuFD** [comment]
@meunicorn 

Thanks for reaching out. We tested these scenarios in our SDK. Works well.

Please check the following and test again.
1. Make sure to upload content of FAQs & Topics in Japanese
2. Make sure to enter content of default strings file in Japanese as mentioned in the iOS documentation.
3. Make sure language of your device is Japanese

Upon setting these configurations, uninstall your app and reinstall. Contents should load in Japanese.


If you are still not seeing content in Japanese, please do the following.
1. Take a screenshot of FAQs in Japanese in Freshchat Agent portal
2. Take a screenshot of Japanese content in your custom bundle
3. Take a screenshot of your app to show us that content is not translated.

Share us these screenshot by email via support@freshchat.com. We will do deeper analysis and help via emails.
