### ISSUE TITLE
Can't type in the support input field

### ISSUE THREAD

**Issue by Mastersam07** [freshworks/freshchat-flutter-sdk#11]
## Describe the bug
After integrating the freshchat plugin, i could not type in the support input field but can only copy and paste.

## Steps to reproduce
```    
* Step 1 - Integrate freshchat plugin version 0.5.0
* Step 2 - Try typing in the input field
```

## Expected behavior
The input field is supposed to take input and then send to support.

## Platform
- [x] Flutter

## Freshchat SDK version
- SDK version : 0.5.0
- Flutter version (if applicable) : 2.0.4

## Device information
- [x] Android
- [x] iPhone 8 plus
- [x] iPhone 11 pro max

**Comment by Mastersam07** [comment]
@rohit-ramkumar any ideas?

**Comment by rohit-ramkumar** [comment]
@Mastersam07 Sorry. I could not understand this issue.
Can you share a video of this issue?

**Comment by Mastersam07** [comment]
@rohit-ramkumar here is the video


https://user-images.githubusercontent.com/31275429/117149174-e1d9e380-adae-11eb-97e0-8047b626b94d.mp4

I can't type into the window meant to send message to freshchat. I can only paste there

**Comment by rohit-ramkumar** [comment]
@Mastersam07  the video uploaded is not playing / seems to be corrupted, can you upload again?

**Comment by Mastersam07** [comment]
https://drive.google.com/file/d/14ywzM-f_knzi8i6Fu4VlYbh6ngyNgAGB/view?usp=sharing. I uploaded a new one on github but i could not play it also.

Here is the video @rohit-ramkumar

**Comment by MuthuFD** [comment]
@Mastersam07 Is this happening in Emulator or Real device?
Can you give us details about the test device model, iOS OS versions

**Comment by MuthuFD** [comment]
Hope you were able to solve this issue.
If you are still facing this issue, please reach out to us through support@freshchat.com
