### ISSUE TITLE
push: Client side integration - Android can't display notification

### ISSUE THREAD

**Issue by linversion** [freshworks/freshchat-flutter-sdk#12]
## Describe the bug
I am integrating Freshchat push notification in my flutter application. It can display notification when on foreground but not working when on background. 
## Steps to reproduce

* Step 1 - setup push token
```dart
//main.dart
var messaging = FirebaseMessaging.instance;
await messaging.requestPermission();
var token = await messaging.getToken();
Freshchat.setPushRegistrationToken(token);
```

* Step 2 - listen foreground message
```dart
//main.dart
FirebaseMessaging.onMessage.listen((RemoteMessage message){

  if('freshchat_user' == message.data['source']) {
    Freshchat.handlePushNotification(message.data);
  }
});
```

* Step3 - listen background message
```dart
//main.dart
FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);

//top level function
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  print('Handling a background message: ${message.data}');
  if('freshchat_user' == message.data['source']) {
    Freshchat.handlePushNotification(message.data);
  }
}
//got one exception
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method handlePushNotification on channel freshchat_sdk)
E/flutter (21784): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
E/flutter (21784): <asynchronous suspension>
E/flutter (21784): #1      Freshchat.handlePushNotification (package:freshchat_sdk/freshchat_sdk.dart:381:5)
```
I had checked out the doc, it seems like I missed the following step. 
![image](https://user-images.githubusercontent.com/37201297/117394721-3e610e00-af29-11eb-81fb-b44c7832718c.png)
But I don't know how to register the Freshchat SDK plugin.

## Expected behavior
display background message notification

## Platform
- [ ] Android

## Freshchat SDK version
- SDK version : 0.5.0
- Flutter version (if applicable) :  2.0
- firebase_messaging: ^9.1.3
```
Provide device details here like
 * Device name oneplus 9R
 * OS version android 11

```

## Crash log
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method handlePushNotification on channel freshchat_sdk)
E/flutter (21784): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
E/flutter (21784): <asynchronous suspension>
E/flutter (21784): #1      Freshchat.handlePushNotification (package:freshchat_sdk/freshchat_sdk.dart:381:5)

**Comment by rohit-ramkumar** [comment]
Hi @linversion 

1. Inside your Android Application class,  add the following code along with other imports. 
 `import com.freshchat.consumer.sdk.flutter.FreshchatSdkPlugin;`
2. Inside your Android Application class, you will find `registerWith` method. In that method add, the following code. `FreshchatSdkPlugin.register(registry);`
3. Replace `freshchat_user == message.data['source']` with `Freshchat.isFreshchatNotification(message['data'])`
4. Please make sure you are testing in real test device and not emulator to check background notifications.

**Comment by linversion** [comment]
> Hi @linversion
> 
> 1. Inside your Android Application class,  add the following code along with other imports.
>    `import com.freshchat.consumer.sdk.flutter.FreshchatSdkPlugin;`
> 2. Inside your Android Application class, you will find `registerWith` method. In that method add, the following code. `FreshchatSdkPlugin.register(registry);`
> 3. Replace `freshchat_user == message.data['source']` with `Freshchat.isFreshchatNotification(message['data'])`
> 4. Please make sure you are testing in real test device and not emulator to check background notifications.

Hi @rohit-ramkumar 
I add the `FreshchatSdkPlugin.register(registry);` in the `registerWith` method. Here is my application:
![image](https://user-images.githubusercontent.com/37201297/117531222-20240c80-b014-11eb-84d2-5b495cbba876.png)
My AndroidManifest.xml:
![image](https://user-images.githubusercontent.com/37201297/117531255-48137000-b014-11eb-86a4-b23f46aeefd6.png)
My backgroundMessageHandler function:
![image](https://user-images.githubusercontent.com/37201297/117531338-a3ddf900-b014-11eb-8505-2206de2ba9a3.png)

But I still got this exception when a new message arriving.
```
FlutterFire Messaging: An error occurred in your background messaging handler:
I/flutter (28812): MissingPluginException(No implementation found for method isFreshchatNotification on channel freshchat_sdk)
```
Please provider a demo if possible. Thank you.

**Comment by rohit-ramkumar** [comment]
@linversion  please add this inside the `registerWith` method
`       FirebaseMessagingPlugin.registerWith(registry.registrarFor("io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin"));
`
also please make sure you have added the firebasemessaging dependency for the android app when using the above
 
We are currently working on a demo app, will be uploading it in upcoming days

**Comment by MuthuFD** [comment]
Hope our above suggestion solves your queries.
If you need more help, please contact us through support@freshchat.com
