### ISSUE TITLE
'Please create user first' error while setting new user

### ISSUE THREAD

**Issue by matszafraniec** [freshworks/freshchat-flutter-sdk#4]
## Describe the bug
When I'm trying to call Freshchat.setUser(user) method, freshchatSDK returns me below output:

_E/FRESHCHAT( 7532): Exception on samsung SM-J330F Android API 9 (28) >>>>> sc: 418 m: {"success":false,"errorCode":1,"errorMessage":"Please create the user first"}
E/FRESHCHAT( 7532): com.freshchat.consumer.sdk.e.b: sc: 418 m: {"success":false,"errorCode":1,"errorMessage":"Please create the user first"}_

## Steps to reproduce
Here is my code:

```dart
void initSupportConversation() async {
    final freshchatUser = FreshchatUser('123', '123');

    freshchatUser.setFirstName('John');
    freshchatUser.setEmail('John@email.com');
    freshchatUser.setPhone('965', '51523094');

    Freshchat.setUser(freshchatUser);

    final user = await Freshchat.getUser;

    print(user.getPhone());
  }
  ```
  
  btw. print returns proper user phone number.

## Platform
- [X] Android

## Freshchat SDK version
- SDK version : 0.4.0 
- Flutter version (if applicable) : 1.22.6
- OS version: Android 9

## Crash log
E/FRESHCHAT( 7532): Exception on samsung SM-J330F Android API 9 (28) >>>>> sc: 418 m: {"success":false,"errorCode":1,"errorMessage":"Please create the user first"}
E/FRESHCHAT( 7532): com.freshchat.consumer.sdk.e.b: sc: 418 m: {"success":false,"errorCode":1,"errorMessage":"Please create the user first"}
E/FRESHCHAT( 7532): 	at com.freshchat.consumer.sdk.e.a.b(Unknown Source:97)
E/FRESHCHAT( 7532): 	at com.freshchat.consumer.sdk.service.c.c.b(Unknown Source:66)
E/FRESHCHAT( 7532): 	at com.freshchat.consumer.sdk.service.c.c.b(Unknown Source:193)
E/FRESHCHAT( 7532): 	at com.freshchat.consumer.sdk.service.c.c.b(Unknown Source:2)
E/FRESHCHAT( 7532): 	at com.freshchat.consumer.sdk.service.b.b.b(Unknown Source:45)
E/FRESHCHAT( 7532): 	at com.freshchat.consumer.sdk.service.FreshchatService.onHandleIntent(Unknown Source:90)
E/FRESHCHAT( 7532): 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:76)

**Comment by rohit-ramkumar** [comment]
Hi @matszafraniec 
This issue happens when FreshchatUser object is created with constructor
Please use this approach instead

`void initSupportConversation() async {
    final freshchatUser = Freshchat.getUser;
    freshchatUser.setFirstName('John');
    freshchatUser.setEmail('John@email.com');
    freshchatUser.setPhone('965', '51523094');
    Freshchat.setUser(freshchatUser);
    final user = await Freshchat.getUser();
    print(user.getPhone());
  }`
  
  Please let us know if the issue persists after this
