### ISSUE TITLE
[iOS] Update Client side integration of Push Notifications with AppDelegate.swift

### ISSUE THREAD

**Issue by matszafraniec** [freshworks/freshchat-flutter-sdk#6]
## Problem Description
I have a problem with implementing iOS integration, because in documentation (refer here: https://support.freshchat.com/support/solutions/articles/50000003343-freshchat-flutter-sdk-integration-steps) under point 6.1.3 platform implementation is described with Objective-C instead of Swift, which is common approach in Flutter from some time. There is a possibility to update it?

## Describe the solution
Update documentation with Swift codebase.

**Comment by MuthuFD** [comment]
@matszafraniec Please refer our iOS specific documentation here
https://support.freshchat.com/support/solutions/articles/50000000048-freshchat-ios-sdk-integration-steps

Thanks for pointing this out. We will improve this part of the documentation in the coming days.

**Comment by matszafraniec** [comment]
When I can expect updated documentation @MuthuFD ?

**Comment by MuthuFD** [comment]
@matszafraniec You need not wait. You can refer to the push notification section in the iOS document shared above.

Later we will update the same in flutter documentation later.

**Comment by matszafraniec** [comment]
But when I'm trying to implement it with iOS docs, it throws me an error described here: https://github.com/freshworks/freshchat-flutter-sdk/issues/7#issuecomment-813970282

**Comment by MuthuFD** [comment]
@matszafraniec 
For that issue we will soon update an example flutter app with swift implementation. 
Once done, we will update in that ticket.

Give a weeks time for building the example app.

**Comment by daadu** [comment]
@matszafraniec This is how my working `AppDelegate.swift` looks, if you are looking for reference:

```swift
import UIKit
import Flutter

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
    override func application(
        _ application: UIApplication,
        didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
    ) -> Bool {
        // for firebase_messaging [https://pub.dev/packages/firebase_messaging/versions/6.0.13]
        if #available(iOS 10.0, *) {
            UNUserNotificationCenter.current().delegate = self as UNUserNotificationCenterDelegate
        }
        
        GeneratedPluginRegistrant.register(with: self)
        return super.application(application, didFinishLaunchingWithOptions: launchOptions)
    }


    // for freshchat_sdk [https://support.freshchat.com/support/solutions/articles/50000003343-freshchat-flutter-sdk-integration-steps#6.-Push-Notifications]
    override func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        Freshchat.sharedInstance().setPushRegistrationToken(deviceToken)
        super.application(application, didRegisterForRemoteNotificationsWithDeviceToken: deviceToken)
    }

    // for freshchat_sdk [https://support.freshchat.com/support/solutions/articles/50000003343-freshchat-flutter-sdk-integration-steps#6.-Push-Notifications]
    override func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {
        if Freshchat.sharedInstance().isFreshchatNotification(userInfo) {
            Freshchat.sharedInstance().handleRemoteNotification(userInfo, andAppstate: UIApplication.shared.applicationState)
        }
        completionHandler(UIBackgroundFetchResult.noData)
    }
    
    // for freshchat_sdk [https://support.freshchat.com/support/solutions/articles/50000003343-freshchat-flutter-sdk-integration-steps#6.-Push-Notifications]
    @available(iOS 10.0, *)
    override func userNotificationCenter(_ center: UNUserNotificationCenter, didReceive response: UNNotificationResponse, withCompletionHandler completionHandler: @escaping () -> Void) {
        if Freshchat.sharedInstance().isFreshchatNotification(response.notification.request.content.userInfo) {
            Freshchat.sharedInstance().handleRemoteNotification(response.notification.request.content.userInfo, andAppstate: UIApplication.shared.applicationState)
        }
        super.userNotificationCenter(center, didReceive: response, withCompletionHandler: completionHandler)
    }
    
    // for freshchat_sdk [https://support.freshchat.com/support/solutions/articles/50000003343-freshchat-flutter-sdk-integration-steps#6.-Push-Notifications]
    @available(iOS 10.0, *)
    override func userNotificationCenter(_ center: UNUserNotificationCenter, willPresent notification: UNNotification, withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void) {
        if Freshchat.sharedInstance().isFreshchatNotification(notification.request.content.userInfo) {
            Freshchat.sharedInstance().handleRemoteNotification(notification.request.content.userInfo, andAppstate: UIApplication.shared.applicationState)
        }
        super.userNotificationCenter(center, willPresent: notification, withCompletionHandler: completionHandler)
    }
}

```

**Comment by daadu** [comment]
@MuthuFD I am not an iOS developer, but I guess the plugin should add this callbacks by itself (if possible!), so that user does need to add them.

**Comment by matszafraniec** [comment]
Hello @daadu . Thank you for respond, sorry I was not able to check it earlier.

When I've tried to run your code, I received error: `Cannot find 'Freshchat' in scope`. I've tried to add `import Freshchat`, but then it returns `no such module 'Freshchat'`.

Can I ask you to check it again on your side and please tell me which Freshchat package version are you using in your project?

**Comment by matszafraniec** [comment]
@MuthuFD can I ask you when we can expect updated swift implementation with example for Flutter iOS?

**Comment by daadu** [comment]
@matszafraniec I use [my fork(`working` branch)](https://github.com/daadu/freshchat-flutter-sdk/tree/working). It was forked when this package was v0.2.0 or something.

I think they have added those changes, but I have not verified that, still using the forked.

Try it and let me know if any issue.
