### ISSUE TITLE
iOS compile error after implement push notification support

### ISSUE THREAD

**Issue by matszafraniec** [freshworks/freshchat-flutter-sdk#7]
## Describe the bug
After complete tutorial for enabling push notifications on iOS I'm receiving error on compile, presented in crash log section.

## Codebase
Here is my code in AppDelegate.swift

```swift
import UIKit
import Flutter
import Firebase
import GoogleMaps

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)
    GoogleMaps.GMSServices.provideAPIKey("MY_API_KEY")
    
    if #available(iOS 10.0, *) {
      UNUserNotificationCenter.current().delegate = self
    }
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }

  override func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
      Messaging.messaging().apnsToken = deviceToken
      super.application(application, didRegisterForRemoteNotificationsWithDeviceToken: deviceToken)
    }  
  

  func userNotificationCenter(_ center: UNUserNotificationCenter, willPresent notification: UNNotification, withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void) {
       completionHandler([.alert])
  }

  func userNotificationCenter(_ center: UNUserNotificationCenter, didReceive response: UNNotificationResponse, withCompletionHandler completionHandler: @escaping () -> Void) {

  }

  override func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {
    // Objective-C: have to convert to swift
    //  if([[[FreshchatSdkPlugin alloc]init] isFreshchatNotification:info]) {
    // [[FreshchatSdkPlugin alloc]init] handleRemoteNotification:info andAppstate:app.applicationState];
   }
}

```

## Platform
- [X] iOS

## Freshchat SDK version
- Flutter package version : 0.5.0
- Flutter SDK version: 1.22.6

## Crash log
```
Xcode build done.                                           27.7s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    In file included from /Users/mateusz/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/freshchat_sdk-0.5.0/ios/Classes/FreshchatSdkPlugin.m:3:
    /Users/mateusz/Documents/Projects/mashkor_app/ios/Pods/FreshchatSDK/FreshchatSDK/FreshchatSDK.h:289:50: warning: this block declaration is not a prototype [-Wstrict-prototypes]
    -(void)resetUserWithCompletion:(nullable void (^)())completion;
                                                     ^
                                                      void
    /Users/mateusz/Documents/Projects/mashkor_app/ios/Pods/FreshchatSDK/FreshchatSDK/FreshchatSDK.h:286:11: warning: parameter 'Completion' not found in the function declaration [-Wdocumentation]
     * @param Completion block to be called when clearData is completed
              ^~~~~~~~~~
    /Users/mateusz/Documents/Projects/mashkor_app/ios/Pods/FreshchatSDK/FreshchatSDK/FreshchatSDK.h:286:11: note: did you mean 'completion'?
     * @param Completion block to be called when clearData is completed
              ^~~~~~~~~~
              completion
    /Users/mateusz/Documents/Projects/mashkor_app/ios/Pods/FreshchatSDK/FreshchatSDK/FreshchatSDK.h:512:12: warning: parameter 'Array' not found in the function declaration [-Wdocumentation]
     *  @param Array of tags to filter by. Tags can be configured in the portal
               ^~~~~
    /Users/mateusz/Documents/Projects/mashkor_app/ios/Pods/FreshchatSDK/FreshchatSDK/FreshchatSDK.h:514:12: warning: parameter 'Title' not found in the function declaration [-Wdocumentation]
     *  @param Title for the list of filtered view
               ^~~~~
    /Users/mateusz/Documents/Projects/mashkor_app/ios/Pods/FreshchatSDK/FreshchatSDK/FreshchatSDK.h:514:12: note: did you mean 'title'?
     *  @param Title for the list of filtered view
               ^~~~~
               title
    /Users/mateusz/Documents/Projects/mashkor_app/ios/Pods/FreshchatSDK/FreshchatSDK/FreshchatSDK.h:516:12: warning: parameter 'Type' not found in the function declaration [-Wdocumentation]
     *  @param Type can be either Category or Article determining what to show. ( list of filtered articles or categories)
               ^~~~
    /Users/mateusz/Documents/Projects/mashkor_app/ios/Pods/FreshchatSDK/FreshchatSDK/FreshchatSDK.h:516:12: note: did you mean 'type'?
     *  @param Type can be either Category or Article determining what to show. ( list of filtered articles or categories)
               ^~~~
               type
    /Users/mateusz/Documents/Projects/mashkor_app/ios/Pods/FreshchatSDK/FreshchatSDK/FreshchatSDK.h:523:12: warning: parameter 'Array' not found in the function declaration [-Wdocumentation]
     *  @param Array of tags to filter the channels list
               ^~~~~
    /Users/mateusz/Documents/Projects/mashkor_app/ios/Pods/FreshchatSDK/FreshchatSDK/FreshchatSDK.h:525:12: warning: parameter 'Title' not found in the function declaration [-Wdocumentation]
     *  @param Title for the list of filtered channels view
               ^~~~~
    /Users/mateusz/Documents/Projects/mashkor_app/ios/Pods/FreshchatSDK/FreshchatSDK/FreshchatSDK.h:525:12: note: did you mean 'title'?
     *  @param Title for the list of filtered channels view
               ^~~~~
               title
    /Users/mateusz/Documents/Projects/mashkor_app/ios/Pods/FreshchatSDK/FreshchatSDK/FreshchatSDK.h:566:12: warning: parameter 'Array' not found in the function declaration [-Wdocumentation]
     *  @param Array of tags to filter the channels list
               ^~~~~
    /Users/mateusz/Documents/Projects/mashkor_app/ios/Pods/FreshchatSDK/FreshchatSDK/FreshchatSDK.h:568:12: warning: parameter 'Title' not found in the function declaration [-Wdocumentation]
     *  @param Title for the list of filtered channels view
               ^~~~~
    /Users/mateusz/Documents/Projects/mashkor_app/ios/Pods/FreshchatSDK/FreshchatSDK/FreshchatSDK.h:568:12: note: did you mean 'title'?
     *  @param Title for the list of filtered channels view
               ^~~~~
               title
    /Users/mateusz/Documents/Projects/mashkor_app/ios/Pods/FreshchatSDK/FreshchatSDK/FreshchatSDK.h:605:11: warning: parameter 'Enum' not found in the function declaration [-Wdocumentation]
     * @param Enum parameter key for event
              ^~~~
    /Users/mateusz/Documents/Projects/mashkor_app/ios/Pods/FreshchatSDK/FreshchatSDK/FreshchatSDK.h:605:11: note: did you mean 'property'?
     * @param Enum parameter key for event
              ^~~~
              property
    /Users/mateusz/Documents/Projects/mashkor_app/ios/Pods/FreshchatSDK/FreshchatSDK/FreshchatSDK.h:637:12: warning: parameter 'Message' not found in the function declaration [-Wdocumentation]
     *  @param Message text to send to agent
               ^~~~~~~
    /Users/mateusz/Documents/Projects/mashkor_app/ios/Pods/FreshchatSDK/FreshchatSDK/FreshchatSDK.h:637:12: note: did you mean 'message'?
     *  @param Message text to send to agent
               ^~~~~~~
               message
    /Users/mateusz/Documents/Projects/mashkor_app/ios/Pods/FreshchatSDK/FreshchatSDK/FreshchatSDK.h:639:12: warning: parameter 'Tag' not found in the function declaration [-Wdocumentation]
     *  @param Tag of the channel on which the message needs to be sent
               ^~~
    /Users/mateusz/Documents/Projects/mashkor_app/ios/Pods/FreshchatSDK/FreshchatSDK/FreshchatSDK.h:639:12: note: did you mean 'tag'?
     *  @param Tag of the channel on which the message needs to be sent
               ^~~
               tag
    12 warnings generated.
```
Log points that there is something wrong with FreshchatSDK.h. Is it related to package code or I made wrong implementation?

## Additional context
In project I'm using other push notifications provider than FCM.

**Comment by MuthuFD** [comment]
@matszafraniec without push integration was Freshchat SDK integration working without any issues?

**Comment by matszafraniec** [comment]
Thank you for respond @MuthuFD . Yes, without push notification integration Freshchat SDK is working fine.

**Comment by matszafraniec** [comment]
@MuthuFD to be precise: compilator begin throw compilation errors just after I add `import FreshchatSdkPlugin` in AppDelegate.swift.

**Comment by rohit-ramkumar** [comment]
Hi @matszafraniec 
If your native iOS code is in Swift, please add `#import "FreshchatSdkPlugin.h"` in the bridging header file of your project(create one if not present)
Then you can use the methods like this
`let freshchatSdkPlugin = FreshchatSdkPlugin()
     if freshchatSdkPlugin.isFreshchatNotification(userInfo){
        print("is Freshchat Notification")
    }else{
        print("Not Freshchat Notification")
    }
`
Please refer to the files attached 

[swift-sample.zip](https://github.com/freshworks/freshchat-flutter-sdk/files/6348490/swift-sample.zip)

**Comment by matszafraniec** [comment]
Thank you @rohit-ramkumar , you helped me a lot.

Now, my project compiling and building, but I'm not receiving push notifications on iOS, even if app is in foreground or background. There can be an issue if I have other push notifications provider already implemented?

**Comment by rohit-ramkumar** [comment]
@matszafraniec 
if you are using APNS, please make sure whether you have uploaded the APNS certificate in your respective freshchat portal
Refer to this article https://support.freshchat.com/en/support/solutions/articles/50000000047-ios-push-notification-certificate-creation

**Comment by matszafraniec** [comment]
@rohit-ramkumar yes, it was already added.

**Comment by matszafraniec** [comment]
@rohit-ramkumar In addition I'm sending logs generated on app startup. As we can see permissions to push notifications are granted, device token is set and registered.

Xcode build done.                                           63.3s
(lldb) 2021-04-22 12:29:39.071952+0200 Runner[8700:2210627] Pushwoosh: Initializing application runtime
7.3.0 - [Firebase/Core][I-COR000005] No app has been configured yet.
7.3.0 - [Firebase/Messaging][I-FCM001000] FIRMessaging Remote Notifications proxy enabled, will swizzle remote notification receiver handlers. If you'd prefer to manually integrate Firebase Messaging, add "FirebaseAppDelegateProxyEnabled" to your Info.plist, and set it to NO. Follow the instructions at:
https://firebase.google.com/docs/cloud-messaging/ios/client#method_swizzling_in_firebase_messaging
to ensure proper integration.
[PW] HWID: HWID
[PW] [I] -[Pushwoosh] Will show foreground notifications: 1
**grant: true**
[PW] [I] -[PWPushNotificationsManagerCommon] Registered for push notifications: 28cb6f1d7fee49cbd93bc113d90aa2e47055d208a2e54c7b97db41146c27c18f
[PW] [I] -[PWRequestManager]
x
|    Pushwoosh request:
| Url:      https://APP_ID.api.pushwoosh.com/json/1.3/getInApps
| Payload:  {"request":{"device_type":1,"language":"en","application":"APP_ID","userId":"USER_ID","v":"6.1.1","hwid":"HWID"}}
| Status:   "200 no error"
| Response: {"status_code":200,"status_message":"OK","response":{"inApps":[]}}
x
**Device Token 32 bytes
Device token is set**
[PW] [I] -[PWPushNotificationsManagerCommon] Registered for push notifications: 28cb6f1d7fee49cbd93bc113d90aa2e47055d208a2e54c7b97db41146c27c18f
[PW] [D] -[PWInAppMessagesManager] /registerUser with same id already sent this day
[PW] [I] -[PWRequestManager]
x
|    Pushwoosh request:
| Url:      https://APP_ID.api.pushwoosh.com/json/1.3/getConfig
| Payload:  {"request":{"device_type":1,"features":["channels","events"],"application":"APP_ID","userId":"USER_ID","v":"6.1.1","hwid":"HWID"}}
| Status:   "200 no error"
| Response: {"status_code":200,"status_message":"OK","response":{"features":{"channels":{},"events":[]}}}
x
[PW] [I] -[PWRequestManager]
x
|    Pushwoosh request:
| Url:      https://EB148-1E466.api.pushwoosh.com/json/1.3/applicationOpen
| Payload:  {"request":{"jailbroken":0,"notificationTypes":7,"app_version":"3.0.16","application":"APP_ID","device_type":1,"userId":"USER_ID","language":"en","hwid":"HWID","package":"com.mashkor.mobileapp","os_version":"14.4","v":"6.1.1","device_model":"iPhone9,1"}}
| Status:   "200 no error"
| Response: {"status_code":200,"status_message":"OK","response":{"required_inapps":[]}}
x
[PW] [D] -[PWDataManagerCommon] sending appOpen completed
[PW] [I] -[PWRequestManager]
x
|    Pushwoosh request:
| Url:      https://APP_ID.pushwoosh.com/json/1.3/getTags
| Payload:  {"request":{"device_type":1,"application":"APP_ID","userId":"USER_ID","v":"6.1.1","hwid":"HWID"}}
| Status:   "200 no error"
| Response: {"status_code":200,"status_message":"OK","response":{"result":{"Jailbroken":0,"name":"Mateusz0","OS Version":"14.4.0.0","SDK Version":"6.1.1.0","Push Alerts Enabled":1,"Language":"en","Country":"pl","City":"pl, warsaw","Device Model":"iPhone9,1","Application Version":"3.0.16.0","Last Application Open":1619049600,"First Install":1618790400}}}
x
[PW] [D] -[PWDataManagerCommon] loadTags completed
**FRESHCHAT: Push token registered : 28cb6f1d7fee49cbd93bc113d90aa2e47055d208a2e54c7b97db41146c27c18f**
[connection] nw_resolver_start_query_timer_block_invoke [C1] Query fired: did not receive all answers in time for APP_ID.pushwoosh.com:443
Connecting to VM Service at ws://127.0.0.1:62594/GIU4PNHSzLU=/ws
[PW] [D] -[PWNotificationManagerCompatiOS10] NotificationCenter authorization granted: 1
**Device Token 32 bytes
Device token is set**
[PW] [I] -[PWPushNotificationsManagerCommon] Registered for push notifications: 28cb6f1d7fee49cbd93bc113d90aa2e47055d208a2e54c7b97db41146c27c18f
[38;5;244m[GETX] [39;49mInstance "void" has been created
[38;5;244m[GETX] [39;49mInstance "Future<void>" has been created
[connection] nw_resolver_start_query_timer_block_invoke [C2] Query fired: did not receive all answers in time for msdk.freshchat.com:443
[38;5;244m[GETX] [39;49mInstance "GetMaterialController" has been created
[38;5;244m[GETX] [39;49mInstance "GetMaterialController" has been initialized
[38;5;244m[GETX] [39;49mGOING TO ROUTE /
[38;5;244m[GETX] [39;49mInstance "UserRepository" has been created
[38;5;244m[GETX] [39;49mInstance "SplashController" has been created
[38;5;244m[GETX] [39;49mInstance "SplashController" has been initialized
[38;5;244m[Firestore] [39;49m[Read] Looking for customer with specified id in customers collection
[38;5;244m[GETX] [39;49mREPLACE ROUTE /
[38;5;244m[GETX] [39;49mNEW ROUTE /home
[38;5;244m[GETX] [39;49mInstance "ConfigService" has been created
[38;5;244m[GETX] [39;49mInstance "ConfigService" has been initialized
[38;5;244m[GETX] [39;49mInstance "OrdersRepository" has been created
[38;5;244m[GETX] [39;49mInstance "OrderCreatorRepository" has been created
[38;5;244m[GETX] [39;49mInstance "HomeController" has been created
[38;5;244m[GETX] [39;49mInstance "HomeController" has been initialized
**FRESHCHAT: Push token registered : 6542636473503943676b4b586e627a357539484d49643a41504139316246503656336368586d35495f70597835776b3376334f55627656716d75475f6a484145566a6c6c78333433556434427178506776374e6770304471717558724c61375f796f7443377a77735f56667876515645314a2d30354252464d7168754564445330625757676c4268337837634f70306551354b596878744438454963535f7266774445**
[38;5;244m[GETX] [39;49mOPEN DIALOG: 67077998
[38;5;244m[GETX] [39;49mCLOSE DIALOG: 67077998
[connection] nw_resolver_start_query_timer_block_invoke [C3] Query fired: did not receive all answers in time for firebaselogging-pa.googleapis.com:443
color <UIDynamicSystemColor: 0x2801a7680; name = systemBlueColor>
[connection] nw_resolver_start_query_timer_block_invoke [C3] Query fired: did not receive all answers in time for firebaselogging-pa.googleapis.com:443
[tcp] tcp_output [C1.1:3] flags=[R.] seq=2023835843, ack=103008097, win=4095 state=CLOSED rcv_nxt=103008097, snd_una=2023835766

**Comment by rohit-ramkumar** [comment]
@matszafraniec 
Try opening this URL https://{{domain-name}}.freshchat.com/app/api/notif_debug?convId=CONV_ID with CONV_ID as the id of the active conversation which is not receiving push notification.
Conversation ID is present in the URL of the conversation when you load it in agent portal, it would look something like this
https://{{domain-name}}.freshchat.com/a/APP_ID/inbox/1/0/conversation/CONV_ID
Please share the response you receive when you open that URL

**Comment by matszafraniec** [comment]
@rohit-ramkumar thank you. Below you can find response:

`{"user":{"firstName":"Deepa","email":"deepa@mashkor.com","id":476165494471862,"alias":"B9D715F5-76A9-49A8-8B6D-CE099A52C48A","groupAliasSet":[],"phone":"96599262254","ruleMeta":{},"usage_meta":[],"kv_meta":[],"device_meta":[],"notificationId":"6542636473503943676b4b586e627a357539484d49643a41504139316246503656336368586d35495f70597835776b3376334f55627656716d75475f6a484145566a6c6c78333433556434427178506776374e6770304471717558724c61375f796f7443377a77735f56667876515645314a2d30354252464d7168754564445330625757676c4268337837634f70306551354b596878744438454963535f7266774445","notificationType":2,"createdMillis":1619006541424,"updatedMillis":1619088046814,"type":0,"clientVersionCode":0,"clientType":0,"appId":0,"roleId":0,"experienceGroupId":0,"totalSessions":0,"deleted":0,"freshIdActivated":false,"lastSeenMillis":0,"present":false,"isNameGenerated":false,"usePriorityInbox":false,"activeForBillingCycle":false,"manuallyDeactivated":false,"dormantAgent":false,"liveTranslateEnabled":false,"isShadowBanned":false,"hardDeleted":false,"markedForDeletion":false,"isRbacForbidden":false,"jwtAuthStatus":0,"status":0,"maxConvAssignable":0,"unsubscribedFromCampaign":false,"preview":false},"pushSuccessOnServer":true,"pushEnabled":true,"apnsPushResult":{"cert":{"certId":280,"certName":"Push_certificate_p12.p12","production":1,"password":"****","appId":445386311168283,"bundleId":"com.mashkor.mobileapp"},"deliveryError":"BadDeviceToken","apnsMessage":"SimpleApnsPushNotification [token=6542636473503943676b4b586e627a357539484d49643a41504139316246503656336368586d35495f70597835776b3376334f55627656716d75475f6a484145566a6c6c78333433556434427178506776374e6770304471717558724c61375f796f7443377a77735f56667876515645314a2d30354252464d7168754564445330625757676c4268337837634f70306551354b596878744438454963535f7266774445, payload={\"aps\":{\"badge\":1,\"alert\":{\"body\":\"{\\\"source\\\":\\\"freshchat_user\\\"}\"},\"sound\":\"default\"}}, invalidationTime=Fri Apr 23 00:00:00 UTC 2021, priority=IMMEDIATE, topic=com.mashkor.mobileapp, apns-collapse-id=null]","exceptionMessage":""}}`

**Comment by rohit-ramkumar** [comment]
@matszafraniec 
In the response, i can see `"deliveryError":"BadDeviceToken"`
Please check your certificate and build (whether debug or prod both should be of the same type), both should be the same

**Comment by matszafraniec** [comment]
Certificate is uploaded properly. We are using it in our push notification provider and notifications comes from there properly. I've double checked bundle id and password. I've tried in release mode and debug mode, but still can't receive notifications.

Current response:
`{"user":{"firstName":"Deepa","email":"deepa@mashkor.com","id":476835140760230,"alias":"1E1EFAAB-4F1E-420F-8A0E-B407513E8833","groupAliasSet":[],"phone":"96599262254","ruleMeta":{},"usage_meta":[],"kv_meta":[],"device_meta":[],"notificationId":"28cb6f1d7fee49cbd93bc113d90aa2e47055d208a2e54c7b97db41146c27c18f","notificationType":2,"createdMillis":1619170029288,"updatedMillis":1619171244881,"type":0,"clientVersionCode":0,"clientType":0,"appId":0,"roleId":0,"experienceGroupId":0,"totalSessions":0,"deleted":0,"freshIdActivated":false,"lastSeenMillis":0,"present":false,"isNameGenerated":false,"usePriorityInbox":false,"activeForBillingCycle":false,"manuallyDeactivated":false,"dormantAgent":false,"liveTranslateEnabled":false,"isShadowBanned":false,"hardDeleted":false,"markedForDeletion":false,"isRbacForbidden":false,"jwtAuthStatus":0,"status":0,"maxConvAssignable":0,"unsubscribedFromCampaign":false,"preview":false},"pushSuccessOnServer":true,"pushEnabled":true,"apnsPushResult":{"cert":{"certId":286,"certName":"Push_certificate.p12","production":1,"password":"****","appId":445329817433374,"bundleId":"com.mashkor.mobileapp"},"deliveryError":"BadDeviceToken","apnsMessage":"SimpleApnsPushNotification [token=28cb6f1d7fee49cbd93bc113d90aa2e47055d208a2e54c7b97db41146c27c18f, payload={\"aps\":{\"badge\":1,\"alert\":{\"body\":\"{\\\"source\\\":\\\"freshchat_user\\\"}\"},\"sound\":\"default\"}}, invalidationTime=Sat Apr 24 00:00:00 UTC 2021, priority=IMMEDIATE, topic=com.mashkor.mobileapp, apns-collapse-id=null]","exceptionMessage":""}}`

@rohit-ramkumar

**Comment by rohit-ramkumar** [comment]
@matszafraniec 
This means that certificate either certificate environment is incorrect or token not sent correctly. Please check correct environment while uploading push certificate in Freshchat. 
For dev environment make sure "Production Environment" checkbox should be unchecked and checked for production.

**Comment by matszafraniec** [comment]
It has started working, when I made production release. Thank you for help @rohit-ramkumar .

Issue resolved.
