### ISSUE TITLE
Exception has occurred. StateError (Bad state: Stream has already been listened to.)

### ISSUE THREAD

**Issue by carman247** [freshworks/freshchat-flutter-sdk#8]
I'm having trouble cancelling/closing the stream subscription ..

Even though I'm defining and setting only once and calling "cancel" I still get this error when signing in again as the same user or another ...

`Exception has occurred.
StateError (Bad state: Stream has already been listened to.)`

I'm trying to listen to this event:

`Freshchat.onRestoreIdGenerated.listen
`

**Comment by rohit-ramkumar** [comment]
@carman247 Hi,
Please make sure you are calling cancel on StreamSubscription
` StreamSubscription restoreStreamSubscription = Freshchat.onRestoreIdGenerated.listen;`

**Comment by carman247** [comment]
@rohit-ramkumar thanks for the reply,

I thought I was doing that but maybe it wasn't being called properly ...

Is there a way to view all open/active StreamSubscriptions for a particular stream?

**Comment by rohit-ramkumar** [comment]
@carman247 on further analysis, this issue happens when we add more than 1 listener to a stream
As a temporary fix, you can go about it like this 
`StreamSubscription restoreStreamSubscription = Freshchat.onRestoreIdGenerated.asBroadcastStream().listen; restoreStreamSubscription.cancel()`

**Comment by carman247** [comment]
@rohit-ramkumar thanks, and no problem - I wasn't sure if it was an issue or just something I was doing wrong :)
