### ISSUE TITLE
how to keep listen unread count when not in chat page?

### ISSUE THREAD

**Issue by linversion** [freshworks/freshchat-flutter-sdk#9]
## Problem Description
I need to show a red dot in my home page when there is a unread message. How to do that?

**Comment by rohit-ramkumar** [comment]
Hi @linversion 
You can listen to onMessageCountUpdate stream which gets triggered for new unread messages , implementation can be done like this
` var unreadCountStream = Freshchat.onMessageCountUpdate;
    StreamSubscription unreadCountSubscription = unreadCountStream.listen((event){
      print("New message generated: " + event.toString());
    });`

**Comment by linversion** [comment]
Hi rohit-ramkumar, I have tried your code before but it didn't work unless you are in the conversations/chatting page. 
![image](https://user-images.githubusercontent.com/37201297/115668656-f7481a00-a379-11eb-8b4d-4d0af4b02887.png)

**Comment by linversion** [comment]
> Hi rohit-ramkumar, I have tried your code before but it didn't work unless you are in the conversations/chatting page.
> ![image](https://user-images.githubusercontent.com/37201297/115668656-f7481a00-a379-11eb-8b4d-4d0af4b02887.png)



> Hi @linversion
> You can listen to onMessageCountUpdate stream which gets triggered for new unread messages , implementation can be done like this
> ` var unreadCountStream = Freshchat.onMessageCountUpdate; StreamSubscription unreadCountSubscription = unreadCountStream.listen((event){ print("New message generated: " + event.toString()); });`

Hi rohit-ramkumar, I have tried your code before but it didn't work unless you are in the conversations/chatting page.
![image](https://user-images.githubusercontent.com/37201297/115668759-13e45200-a37a-11eb-9cca-b3027a97e29c.png)

**Comment by rohit-ramkumar** [comment]
@linversion 
Have you integrated push notifications? Unread count will update instantly only if push notifications are integrated. Please integrate push notifications.
Regarding locale change, SDK automatically reads the app / device locale and loads FAQs and topic details. App locale has more priority than device locale.
